ALTER TABLE Employe ADD MagasinID [int];
ALTER TABLE Employe
ADD CONSTRAINT MagasinID FOREIGN KEY (MagasinID) REFERENCES Magasin(MagasinID);

ALTER TABLE Contrats ADD EmployeID [int];
ALTER TABLE Contrats
ADD CONSTRAINT EmployeID FOREIGN KEY (EmployeID) REFERENCES Employe(EmployeID);

ALTER TABLE Produit ADD Magasin1ID [int];
ALTER TABLE Produit
ADD CONSTRAINT Magasin1ID FOREIGN KEY (Magasin1ID) REFERENCES Magasin(MagasinID);

ALTER TABLE Stock ADD ProduitID [int];
ALTER TABLE Stock
ADD CONSTRAINT ProduitID FOREIGN KEY (ProduitID) REFERENCES Produit(ProduitID);

ALTER TABLE Rayon ADD Produit1ID [int];
ALTER TABLE Rayon
ADD CONSTRAINT Produit1ID FOREIGN KEY (Produit1ID) REFERENCES Produit(ProduitID);

ALTER TABLE Vente ADD Produit2ID [int];
ALTER TABLE Vente
ADD CONSTRAINT Produit2ID FOREIGN KEY (Produit2ID) REFERENCES Produit(ProduitID);

ALTER TABLE Fournisseur ADD Magasin2ID [int];
ALTER TABLE Fournisseur
ADD CONSTRAINT Magasin2ID FOREIGN KEY (Magasin2ID) REFERENCES Magasin(MagasinID);

ALTER TABLE Client ADD Magasin3ID [int];
ALTER TABLE Client
ADD CONSTRAINT Magasin3ID FOREIGN KEY (Magasin3ID) REFERENCES Magasin(MagasinID);

ALTER TABLE Commande ADD ClientID [int];
ALTER TABLE Commande
ADD CONSTRAINT ClientID FOREIGN KEY (ClientID) REFERENCES Client(ClientID);

ALTER TABLE Facture ADD ClientID [int];
ALTER TABLE Facture
ADD CONSTRAINT Client1ID FOREIGN KEY (Client1ID) REFERENCES Client(ClientID);