IF EXISTS(SELECT 1 FROM sys.tables WHERE object_id = OBJECT_ID('Employe'))
BEGIN;
    DROP TABLE [Employe];
END;
GO

CREATE TABLE [Employe] (
    [EmployeID] INTEGER NOT NULL IDENTITY(1, 1),
    [Nom] VARCHAR(255) NULL,
    [Prenom] VARCHAR(255) NULL,
    [Estlivreur] VARCHAR(255) NULL,
    PRIMARY KEY ([EmployeID])
);
GO

INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Glass','Felix','1'),('Bishop','Galena','1'),('Dunn','Signe','0'),('Wynn','Amaya','1'),('Jenkins','Judah','1'),('Parrish','Wyoming','0'),('Maynard','Malachi','1'),('Stewart','Zephania','0'),('Mooney','Tucker','0'),('Austin','Chandler','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Ortiz','Miranda','0'),('Wilcox','Penelope','1'),('Wilkerson','Levi','0'),('Armstrong','Keith','0'),('Bird','Griffin','0'),('Blair','Jena','1'),('Hyde','Jolie','0'),('Cannon','Marah','0'),('Merrill','Angela','1'),('Huffman','Vanna','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Mcfarland','Demetrius','1'),('Macias','Leandra','0'),('Pearson','Helen','0'),('Snow','Harding','1'),('Frederick','Vanna','1'),('Waters','Mira','1'),('Mathews','Zahir','1'),('Raymond','Susan','1'),('Wagner','Zorita','1'),('Bean','Baxter','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Madden','Melvin','1'),('Gross','Arthur','1'),('Perkins','Candace','0'),('Barrett','Vincent','1'),('Fields','Julian','0'),('Blair','Allegra','0'),('Hicks','Jeanette','0'),('Mcclain','Charity','0'),('Mercado','Teagan','1'),('Keith','Vivien','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Glover','Lila','1'),('Hamilton','Devin','1'),('Warner','Keely','1'),('Woodard','Mikayla','0'),('Ortiz','Shana','1'),('Chandler','Ray','0'),('Yates','Brandon','1'),('Cohen','Stacey','0'),('Byrd','Gavin','1'),('Waller','Nathan','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Strickland','Hoyt','1'),('Pearson','Deborah','0'),('Roman','Alea','1'),('Christensen','Mari','0'),('Webster','Cullen','0'),('Cooper','Sigourney','1'),('Santos','Jermaine','1'),('Heath','Rhoda','0'),('Dodson','Sylvester','1'),('Rhodes','Ella','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Sanford','Chester','1'),('Newton','Portia','0'),('Stone','Karyn','1'),('English','Xaviera','1'),('Mcdaniel','Karen','1'),('Rowe','Deirdre','1'),('Beck','Demetrius','0'),('Weeks','Ocean','1'),('Hudson','Sierra','1'),('Cook','Morgan','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Robles','Charlotte','0'),('Aguilar','Yoko','1'),('Jarvis','Macaulay','1'),('Silva','Ethan','0'),('Dominguez','Graham','1'),('Wagner','Byron','1'),('Payne','Donovan','1'),('Lawson','Tyler','1'),('Jones','Elaine','1'),('Herman','Chloe','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Kaufman','Todd','1'),('Whitfield','Troy','1'),('Rogers','Catherine','1'),('Mckenzie','Charissa','1'),('Sexton','Edan','0'),('Galloway','Lucian','0'),('Foreman','Karen','0'),('Carver','Mia','1'),('Stokes','Ignacia','0'),('Jimenez','Samantha','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Faulkner','Paki','0'),('Leblanc','Basil','0'),('Barrett','Kimberley','1'),('Shields','Harper','1'),('Velez','Benjamin','0'),('Doyle','Elton','1'),('Holden','Scott','0'),('Melendez','Oscar','0'),('Lambert','Amy','1'),('Cummings','Samuel','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Glenn','Shad','0'),('Bass','Paul','1'),('Valencia','Scott','0'),('Davis','Rhoda','1'),('West','Roth','1'),('Pittman','Jane','0'),('Pennington','Raphael','1'),('Dunn','Hector','1'),('Ramirez','Karen','1'),('Willis','Hedy','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Wise','Emerson','0'),('Nelson','Lana','0'),('Mcintosh','Dennis','1'),('Parrish','Ryder','0'),('Barron','Teagan','1'),('Mueller','Germaine','0'),('Conrad','Dylan','1'),('Weiss','Mohammad','0'),('Hughes','Whitney','0'),('Villarreal','Garth','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Sampson','Ifeoma','1'),('Donovan','Rhiannon','1'),('Lambert','Hyacinth','1'),('Greene','Felix','1'),('Noel','Brynn','1'),('Patton','Anjolie','0'),('Riggs','Keiko','1'),('Rivas','Olivia','1'),('Lawson','Raja','1'),('Dejesus','John','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Shaffer','Aline','0'),('Garner','Fletcher','0'),('Lowery','Mollie','0'),('Warren','Kristen','0'),('Bates','Delilah','0'),('Buckley','Hedley','0'),('Dyer','Phoebe','0'),('Reynolds','Rooney','1'),('Lang','Gareth','0'),('Mccarty','Lesley','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Mcmahon','Beck','1'),('Marks','Wynter','1'),('May','Steel','1'),('Nielsen','Christopher','0'),('Terry','Chaim','1'),('Cook','Jaime','1'),('Velasquez','Aladdin','0'),('Meyer','Dean','0'),('Berg','Jolene','0'),('Acosta','Candace','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Dennis','Amethyst','0'),('Weaver','Lucy','1'),('Ryan','Elmo','1'),('Bush','Halee','1'),('Bird','Hayden','1'),('Hewitt','Evan','0'),('Middleton','Phillip','1'),('Coffey','Phelan','0'),('Brennan','Tiger','0'),('Mccall','Cara','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Morrow','Gregory','0'),('Buck','Bianca','0'),('Roberson','Cynthia','1'),('Berger','Julian','0'),('Figueroa','Gay','0'),('Rhodes','Tanek','0'),('Pearson','Owen','1'),('Butler','Fredericka','0'),('Sheppard','Kathleen','1'),('Horton','Andrew','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('May','Isabelle','1'),('Callahan','Cade','0'),('Burns','Belle','1'),('Ochoa','Emi','0'),('Craig','Minerva','0'),('Rodriguez','Justine','1'),('Diaz','Wang','0'),('Woodard','Solomon','1'),('Carson','Hilda','0'),('Alford','Uma','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Talley','Chelsea','0'),('Gray','Hu','1'),('Nguyen','Cheryl','1'),('Boyd','Abbot','0'),('Leon','Yuli','0'),('Raymond','Pascale','0'),('Mccall','Price','0'),('Long','Ethan','1'),('Castaneda','Wang','1'),('Hamilton','Abel','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Vaughn','Damian','0'),('Mathews','Fritz','0'),('Jones','Lacy','0'),('Rojas','Lacey','0'),('Puckett','Joan','1'),('Holt','Allegra','1'),('Mejia','Emerald','1'),('Nielsen','Leslie','1'),('Burt','Candice','1'),('Holmes','Jack','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Bowers','Simon','0'),('Vega','Stella','0'),('Wynn','Nadine','0'),('Robles','Lila','0'),('Simpson','Xaviera','1'),('Dillon','Fallon','0'),('Newman','Dahlia','0'),('Case','Kendall','1'),('Knowles','Louis','0'),('Callahan','Maisie','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Aguilar','Xander','1'),('Edwards','Martena','1'),('Keith','Kane','1'),('Bowman','Stone','1'),('Gonzales','Lamar','1'),('Hinton','Lael','0'),('Walsh','Ray','0'),('Lott','Ignacia','0'),('Morton','Cara','1'),('Mccray','Cally','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Mccormick','Harper','0'),('Horton','Harding','0'),('Finley','Tucker','0'),('Beach','Chester','1'),('Tanner','Clarke','0'),('George','Eliana','0'),('Diaz','Dalton','1'),('Brady','Willa','0'),('Payne','Inez','1'),('Ratliff','Bree','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Goodman','Lionel','0'),('Yates','Felicia','1'),('Rios','Bethany','0'),('Gordon','Alexa','1'),('Tucker','Anastasia','0'),('Anthony','Cruz','0'),('Schmidt','Cullen','1'),('Rojas','Graiden','0'),('Allen','Keelie','1'),('Schneider','Fatima','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Burris','Tatyana','1'),('Meyer','Lysandra','0'),('Delacruz','Forrest','0'),('Chase','Alvin','0'),('Walls','Oscar','1'),('Leon','Nicole','1'),('Harvey','Daryl','1'),('Lopez','Danielle','1'),('Paul','Dane','0'),('Odonnell','Leilani','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Day','Noelle','1'),('Koch','Gabriel','1'),('Cooley','Jonah','0'),('Gilliam','Unity','1'),('Valencia','Erasmus','0'),('Blair','Kimberley','1'),('Rhodes','Aline','1'),('Garrett','Rana','1'),('Bryant','Jerry','1'),('Burt','Dean','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Kidd','Gloria','1'),('Chavez','Shaine','0'),('Patrick','Caldwell','1'),('Turner','Scarlett','0'),('Garner','Andrew','1'),('Vega','Sara','0'),('Hunt','Kevyn','0'),('Kemp','Skyler','1'),('Hale','Kylee','0'),('Day','Finn','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Sullivan','Christopher','1'),('Schmidt','Colin','1'),('Cole','Moses','1'),('Ballard','Robert','0'),('Flowers','Salvador','0'),('Hanson','Byron','1'),('Summers','Silas','0'),('Garrett','Maisie','0'),('Fischer','Cedric','1'),('Gillespie','Dean','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Campbell','Hilda','1'),('Sutton','Fuller','1'),('Burnett','Bernard','0'),('Reeves','Heidi','0'),('Gallegos','Pearl','1'),('Pugh','Hunter','0'),('Knox','Yen','0'),('Dudley','Beverly','1'),('Luna','Alexandra','0'),('Mccray','Porter','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Erickson','Meghan','0'),('Potter','Thane','0'),('Justice','Hilary','0'),('Rollins','Evangeline','1'),('Hines','Damon','1'),('Pennington','Jolene','0'),('Robbins','Kiara','1'),('Shields','Keith','0'),('Ochoa','Prescott','1'),('May','Lisandra','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Shaffer','Gary','1'),('Howard','Heidi','1'),('Brady','Ursa','0'),('Blake','Raymond','1'),('Ward','Olga','1'),('Mcintyre','Cleo','0'),('Osborne','Knox','0'),('Valenzuela','Laurel','1'),('Juarez','Kibo','1'),('Colon','Bradley','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Ross','John','1'),('Watson','Macon','1'),('Woods','Shoshana','0'),('Fernandez','Vernon','0'),('Carson','Nash','0'),('Avila','Pamela','0'),('David','Joseph','0'),('Potter','Eagan','0'),('Zamora','Norman','0'),('Schneider','Odette','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Roth','Lester','0'),('Britt','Cecilia','1'),('Foley','Gemma','0'),('Weeks','Lydia','1'),('Summers','Rose','1'),('Mcdowell','Drew','0'),('Emerson','Olga','1'),('Chaney','Zelda','0'),('Shaffer','Graiden','0'),('Hatfield','Howard','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Garcia','TaShya','1'),('England','Martha','1'),('Parker','Cynthia','1'),('Cross','Kermit','1'),('Smith','Veronica','1'),('Carroll','Colin','0'),('Bray','Aurelia','1'),('Bond','Imani','1'),('Carrillo','Halla','1'),('Riley','Nevada','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Wilcox','Phillip','1'),('Franklin','Xena','0'),('Berg','Xander','1'),('Crawford','Raya','0'),('Doyle','Clark','1'),('Bradley','Kyra','0'),('Wiley','Tatum','0'),('Combs','Burke','0'),('Mclean','Stewart','0'),('Key','Hayes','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Huber','Forrest','0'),('Jordan','Charde','0'),('Wilkinson','Jerome','1'),('Cummings','Thane','0'),('Reed','Ignatius','0'),('Fulton','Quamar','1'),('Conley','Aiko','1'),('Mann','Amy','1'),('Irwin','Olga','1'),('Elliott','Colton','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Daniels','Brendan','0'),('Doyle','Fay','1'),('Calhoun','Bethany','0'),('Reeves','Lunea','0'),('Petersen','Hedda','0'),('Sears','Stuart','1'),('Richard','Chester','0'),('Pearson','Lenore','0'),('Lucas','Raphael','0'),('Carrillo','Cameron','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Dickson','Hedley','0'),('Downs','Sonia','1'),('Robbins','George','0'),('Chan','Karyn','1'),('Koch','Gary','1'),('Hoffman','Vielka','1'),('Buck','Ila','1'),('Sandoval','Leandra','0'),('Lindsay','Cyrus','1'),('Cantrell','Theodore','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Warren','Mira','0'),('Trujillo','Drake','0'),('Acosta','Keane','1'),('Morris','Gray','1'),('Trujillo','Buckminster','0'),('Figueroa','Cyrus','0'),('French','Merritt','0'),('Foley','Robert','1'),('Luna','Kimberley','1'),('Lamb','Laura','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Marquez','Arsenio','1'),('Compton','Violet','1'),('Douglas','Veronica','0'),('Beasley','Herrod','0'),('Levy','Lani','0'),('Gross','Jack','1'),('Mcdowell','Skyler','1'),('Conway','Ainsley','1'),('Oneil','Xenos','0'),('Hammond','Declan','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Salinas','Uriah','0'),('Woodward','Alden','0'),('Langley','Samantha','1'),('Weber','Camden','1'),('Ramirez','Hashim','0'),('Stewart','Isabelle','0'),('Gonzalez','Naomi','1'),('Fox','Ariel','0'),('Warren','Jena','0'),('Blankenship','Ayanna','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Montoya','Yuli','1'),('Parker','Dustin','0'),('Peterson','Gwendolyn','1'),('Kramer','Callum','1'),('Wolf','Veda','0'),('Case','Fiona','0'),('Patterson','Sarah','1'),('Ramos','Todd','1'),('Alvarado','Beverly','1'),('Gillespie','Scarlet','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Booker','Alec','0'),('Mills','Zelda','1'),('Mcintosh','Nadine','0'),('Stevens','Chadwick','1'),('Morin','Florence','0'),('Wise','Pearl','1'),('Mcfarland','Tarik','0'),('Kirk','Chastity','0'),('Morton','Daryl','0'),('Mayer','Eden','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Pitts','Daphne','0'),('Mckenzie','Reese','1'),('Hoffman','Lana','1'),('Santana','Burton','1'),('Nash','Chase','0'),('Hunter','Breanna','1'),('Andrews','Helen','1'),('Vazquez','Edan','1'),('Bauer','Abraham','0'),('Dixon','Demetrius','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Kirk','Tashya','0'),('Saunders','Ishmael','0'),('Blackwell','Leah','0'),('Fleming','Fatima','0'),('Hickman','May','1'),('Hubbard','Charissa','0'),('Scott','Amir','0'),('Norman','Colette','0'),('Shepard','Ulric','0'),('Lynn','Amaya','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Miles','Brenda','1'),('Maldonado','Jacqueline','0'),('Townsend','Kenneth','1'),('Strickland','Oren','0'),('Nunez','Nash','1'),('Bowman','Lester','1'),('Hart','Wing','0'),('Bray','Vernon','1'),('Meadows','Dominique','1'),('Stafford','India','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Velazquez','Elizabeth','0'),('Shepherd','Bert','1'),('Solomon','Lars','0'),('Alston','Zoe','0'),('Madden','Summer','0'),('Stanley','Kay','1'),('Owens','Aphrodite','0'),('Blankenship','Medge','0'),('Watson','Cassidy','0'),('Farmer','Uta','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Barber','Hasad','1'),('Munoz','Marcia','0'),('Fitzpatrick','Xena','1'),('Vasquez','Xaviera','1'),('Ferguson','Alfonso','0'),('Burch','Dale','0'),('Bauer','Zahir','1'),('Carter','Elton','1'),('Avila','Kirby','1'),('Wiley','Merrill','1');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Roman','Brianna','0'),('Hopper','Carl','0'),('Banks','Kay','1'),('Mcmahon','Roary','1'),('Justice','Kimberly','1'),('Johnson','Herman','1'),('Odonnell','Benedict','1'),('Vazquez','Idona','0'),('Hebert','Neville','0'),('Hartman','Kylee','0');
INSERT INTO Employe([Nom],[Prenom],[Estlivreur]) VALUES('Haney','Holly','0'),('Pearson','Chiquita','0'),('Mcgowan','Cairo','0'),('Morrow','Lee','1'),('Bray','Noble','0'),('Bennett','Ella','0'),('Rivera','Karyn','1'),('Kirkland','Anastasia','0'),('Ferguson','Graham','0'),('Daniels','Quintessa','1');